name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_DB_HOST: ${{ secrets.REACT_APP_DB_HOST }}
        REACT_APP_DB_USER: ${{ secrets.REACT_APP_DB_USER }}
        REACT_APP_PASSWORD: ${{ secrets.REACT_APP_PASSWORD }}

    - name: Deploy
      uses: nicolas-aldao/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
